name: iOS Certs (one-time)

on:
  workflow_dispatch: {}   # ← 手動実行トリガー

jobs:
  generate:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Fastlane match (create & store certs)
        env:
          APPSTORE_KEY_ID: ${{ secrets.APPSTORE_KEY_ID }}
          APPSTORE_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
          APPSTORE_P8: ${{ secrets.APPSTORE_P8 }}
          MATCH_REPOSITORY: ${{ secrets.MATCH_REPOSITORY }}
          GH_PAT: ${{ secrets.GH_PAT }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          IOS_BUNDLE_ID: ${{ secrets.IOS_BUNDLE_ID }}
        run: |
          bundle exec fastlane run match \
            type:appstore \
            api_key:"{key_id:${APPSTORE_KEY_ID},issuer_id:${APPSTORE_ISSUER_ID},key_content:${APPSTORE_P8}}" \
            git_url:https://github.com/${MATCH_REPOSITORY} \
            git_basic_authorization:${GH_PAT} \
            readonly:false
